services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/public/:/var/www/html

  php-fpm:
    container_name: php-fpm
    build: ./docker/docker_php
    volumes:
      - .:/var/www/html

  postgres:
    container_name: postgres_db
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}